# Generated by Django 3.0.5 on 2021-08-17 19:31

from django.db import migrations, models
import djongo.models.fields
import mongotestbase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('department', models.IntegerField()),
                ('countries', djongo.models.fields.ArrayField(model_container=mongotestbase.models.CountryDetected)),
            ],
        ),
        migrations.CreateModel(
            name='EntryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('authors', djongo.models.fields.ArrayField(model_container=mongotestbase.models.Author, model_form_class=mongotestbase.models.AuthorForm)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
            ],
        ),
    ]
